### ISSUE TITLE
Should client files require appropriate gax stubs?

### ISSUE THREAD

**Issue by samphippen** [googleapis/gapic-generator-ruby#148]
Got this error while requiring a generated client file:

```ruby
Traceback (most recent call last):
	4: from examples/factories/various_factories_usage.rb:155:in `<main>'
	3: from examples/factories/various_factories_usage.rb:73:in `add_campaigns'
	2: from /Users/samphippen/dev/goog/google-ads-ruby/lib/google/ads/google_ads/factories/v1/services.rb:1390:in `campaign'
	1: from /Users/samphippen/dev/goog/google-ads-ruby/lib/google/ads/google_ads/factories/v1/services.rb:1390:in `new'
/Users/samphippen/dev/goog/google-ads-ruby/lib/google/ads/google_ads/v1/services/campaign_service/client.rb:104:in `initialize': uninitialized constant Google::Gax::Grpc::Stub (NameError)
```

**Comment by samphippen** [comment]
Should say: using a generated client file that has been required, looks like it didn't require the gax stub for me

**Comment by blowmage** [comment]
Are you using the generated Gemfile? It adds the following declaration that is needed to ensure that you are using the in-development version of google-gax:

```ruby
gem "google-gax", github: "googleapis/gax-ruby"
```

**Comment by samphippen** [comment]
Yeah, ok, needed to do that, still haven't quite automated all these things yet.
