### ISSUE TITLE
api-common-protos is out of date

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator-ruby#211]
The `shared/api-common-protos` module is out of date and we're missing some changes related to resources.

Running against master causes the generator to fail (i.e. `bundle exec rake gen`):

```
Caused by:
NoMethodError: undefined method `value_from_values' for nil:NilClass
/Users/jbolinger/.rvm/gems/ruby-2.5.3/gems/protobuf-3.10.0/lib/protobuf/message.rb:179:in `[]'
/Users/jbolinger/Development/gapic-generator-ruby/gapic-generator/lib/gapic/schema/wrappers.rb:578:in `resource'
/Users/jbolinger/Development/gapic-generator-ruby/gapic-generator/templates/default/helpers/presenters/service_presenter.rb:179:in `select'
```

**Comment by blowmage** [comment]
Closed by #212
