### ISSUE TITLE
Some rest verbs (e.g. post) should not require body for Rest Gapic

### ISSUE THREAD

**Issue by viacheslav-rostovtsev** [googleapis/gapic-generator-ruby#574]
e.g. of method:
https://cloud.google.com/compute/docs/reference/rest/v1/instances/stop

e.g.
    self.insert_resource
    @client.stop(instance: @name, zone: $default_zone, project: $default_project)

The error:
Minitest::UnexpectedError: ArgumentError: missing keyword: :body
    /var/lib/gems/2.7.0/gems/gapic-common-0.4.0/lib/gapic/rest/client_stub.rb:88:in `make_post_request'
    /home/georgiie/ruby/google-cloud-ruby/google-cloud-compute-v1/lib/google/cloud/compute/v1/instances/rest/client.rb:2659:in `stop'

**Comment by viacheslav-rostovtsev** [comment]
closed in https://github.com/googleapis/gapic-generator-ruby/pull/575
